name: Coding Hours Report

on:
  workflow_dispatch:
    inputs:
      window_start:
        description: 'Start date for git-hours (YYYY-MM-DD)'
        required: false

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/git-hours
        id: hours
        with:
          window_start: ${{ github.event.inputs.window_start }}
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: git-hours
          path: ${{ steps.hours.outputs.results }}
