name: Organization Coding Hours

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set
        run: echo "matrix=$(jq -c '.repos' docs/repos.json)" >> $GITHUB_OUTPUT

  calculate:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJSON(needs.set-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          path: repo
      - name: Run git-hours
        id: hours
        uses: LabVIEW-Community-CI-CD/coding-hours/.github/actions/git-hours@main
        with:
          window_start: ''
          repo_path: repo
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.repo }}-git-hours
          path: ${{ steps.hours.outputs.results }}
